import 'package:flutter/widgets.dart';
import '../../component_example_models.dart';
import 'calendar_example_1.dart';
import 'calendar_example_2.dart';
import 'calendar_example_3.dart';
import 'calendar_example_4.dart';

const ComponentExample calendarExample1 = ComponentExample(
  title: "Range Calendar Example",
  builder: _buildCalendarExample1,
  code: "import 'package:docs/ui/shadcn/shadcn_ui.dart';\n\n/// Calendar with range selection mode.\n///\n/// Demonstrates navigating months using a custom header and binding\n/// a [CalendarValue] for a date range via [CalendarSelectionMode.range].\nclass CalendarExample1 extends StatefulWidget {\n  const CalendarExample1({super.key});\n\n  @override\n  State<CalendarExample1> createState() => _CalendarExample1State();\n}\n\nclass _CalendarExample1State extends State<CalendarExample1> {\n  // Holds the current selection (start/end) when in range mode.\n  CalendarValue? _value;\n  // Tracks the current month/year view independent of selection.\n  CalendarView _view = CalendarView.now();\n  @override\n  Widget build(BuildContext context) {\n    ShadcnLocalizations localizations = ShadcnLocalizations.of(context);\n    return Card(\n      child: IntrinsicWidth(\n        child: Column(\n          mainAxisSize: MainAxisSize.min,\n          crossAxisAlignment: CrossAxisAlignment.stretch,\n          children: [\n            Row(\n              children: [\n                OutlineButton(\n                  density: ButtonDensity.icon,\n                  onPressed: () {\n                    setState(() {\n                      // Move the calendar view to the previous month.\n                      _view = _view.previous;\n                    });\n                  },\n                  child: const Icon(Icons.arrow_back).iconXSmall(),\n                ),\n                Text('\${localizations.getMonth(_view.month)} \${_view.year}')\n                    .small()\n                    .medium()\n                    .center()\n                    .expanded(),\n                OutlineButton(\n                  density: ButtonDensity.icon,\n                  onPressed: () {\n                    setState(() {\n                      // Move the calendar view to the next month.\n                      _view = _view.next;\n                    });\n                  },\n                  child: const Icon(Icons.arrow_forward).iconXSmall(),\n                ),\n              ],\n            ),\n            const Gap(16),\n            Calendar(\n              value: _value,\n              view: _view,\n              onChanged: (value) {\n                setState(() {\n                  _value = value;\n                });\n              },\n              // Range selection allows choosing a start and end date.\n              selectionMode: CalendarSelectionMode.range,\n            ),\n          ],\n        ),\n      ),\n    );\n  }\n}\n",
);

Widget _buildCalendarExample1(BuildContext context) {
  return const CalendarExample1();
}

const ComponentExample calendarExample2 = ComponentExample(
  title: "Single Calendar Example",
  builder: _buildCalendarExample2,
  code: "import 'package:docs/ui/shadcn/shadcn_ui.dart';\n\n/// Calendar with single-date selection and a \"today\" marker.\n///\n/// Uses [CalendarSelectionMode.single] to allow selecting exactly one date,\n/// and passes `now` to highlight the current day in the view.\nclass CalendarExample2 extends StatefulWidget {\n  const CalendarExample2({super.key});\n\n  @override\n  State<CalendarExample2> createState() => _CalendarExample2State();\n}\n\nclass _CalendarExample2State extends State<CalendarExample2> {\n  CalendarValue? _value;\n  CalendarView _view = CalendarView.now();\n  @override\n  Widget build(BuildContext context) {\n    ShadcnLocalizations localizations = ShadcnLocalizations.of(context);\n    return Card(\n      child: IntrinsicWidth(\n        child: Column(\n          mainAxisSize: MainAxisSize.min,\n          crossAxisAlignment: CrossAxisAlignment.stretch,\n          children: [\n            Row(\n              children: [\n                OutlineButton(\n                  density: ButtonDensity.icon,\n                  onPressed: () {\n                    setState(() {\n                      _view = _view.previous;\n                    });\n                  },\n                  child: const Icon(Icons.arrow_back).iconXSmall(),\n                ),\n                Text('\${localizations.getMonth(_view.month)} \${_view.year}')\n                    .small()\n                    .medium()\n                    .center()\n                    .expanded(),\n                OutlineButton(\n                  density: ButtonDensity.icon,\n                  onPressed: () {\n                    setState(() {\n                      _view = _view.next;\n                    });\n                  },\n                  child: const Icon(Icons.arrow_forward).iconXSmall(),\n                ),\n              ],\n            ),\n            const Gap(16),\n            Calendar(\n              value: _value,\n              view: _view,\n              onChanged: (value) {\n                setState(() {\n                  _value = value;\n                });\n              },\n              selectionMode: CalendarSelectionMode.single,\n              // Provide a \"today\" reference for visual emphasis.\n              now: DateTime.now(),\n            ),\n          ],\n        ),\n      ),\n    );\n  }\n}\n",
);

Widget _buildCalendarExample2(BuildContext context) {
  return const CalendarExample2();
}

const ComponentExample calendarExample3 = ComponentExample(
  title: "Multiple Calendar Example",
  builder: _buildCalendarExample3,
  code: "import 'package:docs/ui/shadcn/shadcn_ui.dart';\n\n/// Calendar with multi-date selection.\n///\n/// [CalendarSelectionMode.multi] allows selecting multiple individual days.\nclass CalendarExample3 extends StatefulWidget {\n  const CalendarExample3({super.key});\n\n  @override\n  State<CalendarExample3> createState() => _CalendarExample3State();\n}\n\nclass _CalendarExample3State extends State<CalendarExample3> {\n  CalendarValue? _value;\n  CalendarView _view = CalendarView.now();\n  @override\n  Widget build(BuildContext context) {\n    ShadcnLocalizations localizations = ShadcnLocalizations.of(context);\n    return Card(\n      child: IntrinsicWidth(\n        child: Column(\n          mainAxisSize: MainAxisSize.min,\n          crossAxisAlignment: CrossAxisAlignment.stretch,\n          children: [\n            Row(\n              children: [\n                OutlineButton(\n                  density: ButtonDensity.icon,\n                  onPressed: () {\n                    setState(() {\n                      _view = _view.previous;\n                    });\n                  },\n                  child: const Icon(Icons.arrow_back).iconXSmall(),\n                ),\n                Text('\${localizations.getMonth(_view.month)} \${_view.year}')\n                    .small()\n                    .medium()\n                    .center()\n                    .expanded(),\n                OutlineButton(\n                  density: ButtonDensity.icon,\n                  onPressed: () {\n                    setState(() {\n                      _view = _view.next;\n                    });\n                  },\n                  child: const Icon(Icons.arrow_forward).iconXSmall(),\n                ),\n              ],\n            ),\n            const Gap(16),\n            Calendar(\n              value: _value,\n              view: _view,\n              onChanged: (value) {\n                setState(() {\n                  _value = value;\n                });\n              },\n              // Multi selection lets users toggle arbitrary dates on/off.\n              selectionMode: CalendarSelectionMode.multi,\n            ),\n          ],\n        ),\n      ),\n    );\n  }\n}\n",
);

Widget _buildCalendarExample3(BuildContext context) {
  return const CalendarExample3();
}

const ComponentExample calendarExample4 = ComponentExample(
  title: "Calendar Example",
  builder: _buildCalendarExample4,
  code: "import 'package:docs/ui/shadcn/shadcn_ui.dart';\n\n/// Calendar in read-only mode (no selection).\n///\n/// [CalendarSelectionMode.none] displays the month grid without allowing\n/// user selections; useful for a visual calendar-only view.\nclass CalendarExample4 extends StatefulWidget {\n  const CalendarExample4({super.key});\n\n  @override\n  State<CalendarExample4> createState() => _CalendarExample4State();\n}\n\nclass _CalendarExample4State extends State<CalendarExample4> {\n  CalendarValue? _value;\n  CalendarView _view = CalendarView.now();\n  @override\n  Widget build(BuildContext context) {\n    ShadcnLocalizations localizations = ShadcnLocalizations.of(context);\n    return Card(\n      child: IntrinsicWidth(\n        child: Column(\n          mainAxisSize: MainAxisSize.min,\n          crossAxisAlignment: CrossAxisAlignment.stretch,\n          children: [\n            Row(\n              children: [\n                OutlineButton(\n                  density: ButtonDensity.icon,\n                  onPressed: () {\n                    setState(() {\n                      _view = _view.previous;\n                    });\n                  },\n                  child: const Icon(Icons.arrow_back).iconXSmall(),\n                ),\n                Text('\${localizations.getMonth(_view.month)} \${_view.year}')\n                    .small()\n                    .medium()\n                    .center()\n                    .expanded(),\n                OutlineButton(\n                  density: ButtonDensity.icon,\n                  onPressed: () {\n                    setState(() {\n                      _view = _view.next;\n                    });\n                  },\n                  child: const Icon(Icons.arrow_forward).iconXSmall(),\n                ),\n              ],\n            ),\n            const Gap(16),\n            Calendar(\n              value: _value,\n              view: _view,\n              onChanged: (value) {\n                setState(() {\n                  _value = value;\n                });\n              },\n              now: DateTime.now(),\n              // Disable all selection (view-only).\n              selectionMode: CalendarSelectionMode.none,\n            ),\n          ],\n        ),\n      ),\n    );\n  }\n}\n",
);

Widget _buildCalendarExample4(BuildContext context) {
  return const CalendarExample4();
}

const List<ComponentExample> calendarExamples = [
  calendarExample1,
  calendarExample2,
  calendarExample3,
  calendarExample4,
];