/// Global token override entrypoint for the slider component.
class SliderThemeTokensConfig {
  const SliderThemeTokensConfig._();

  /// Global component theme override for `SliderTheme`.
  static Object? global;
  static const String globalType = 'SliderTheme';
  static const Map<String, Object?> globalDefaults = <String, Object?>{
    'trackHeight': null,
    'trackRadius': null,
    'thumbInset': null,
    'thumbSize': null,
    'thumbRadius': null,
    'thumbEdgeOffsetPx': null,
    'thumbVerticalOffsetPx': null,
    'joinGapPx': null,
    'fillStopsAtThumbCenter': null,
    'fillEdgeBiasPx': null,
    'preset': null,
    'trackBuilder': null,
    'fillBuilder': null,
    'thumbBuilder': null,
    'ticksBuilder': null,
    'overlayBuilder': null,
    'segmentLayout': null,
    'trackRenderer': null,
    'dragPopoverBuilder': null,
    'dragPopoverOffset': null,
    'dragPopoverVisibility': null,
    'popoverShape': null,
    'popoverBackgroundColor': null,
    'popoverForegroundColor': null,
    'guideColor': null,
    'fillActiveColor': null,
    'fillInactiveColor': null,
    'thumbFillColor': null,
    'thumbBorderColor': null,
    'dotsActiveColor': null,
    'dotsInactiveColor': null,
    'waveformTicksActiveColor': null,
    'waveformTicksInactiveColor': null,
    'waveHeight': null,
    'wavePadding': null,
    'waveBarWidth': null,
    'waveBarGap': null,
    'waveMinBarHeight': null,
    'waveMaxBarHeight': null,
    'waveCornerRadius': null,
    'waveActiveColor': null,
    'waveInactiveColor': null,
    'waveDisabledOpacity': null,
    'waveShowThumb': null,
    'waveThumbRadius': null,
    'waveThumbColor': null,
    'waveThumbBorderColor': null,
    'waveThumbBorderWidth': null,
    'waveHitSlop': null,
    'waveEnabled': null,
    'wavePopoverBuilder': null,
    'wavePopoverOffset': null,
    'wavePopoverVisibility': null,
  };
  static const Map<String, Object?> globalTokens = <String, Object?>{};
}
