/// Global token override entrypoint for the slider component.
class SliderThemeTokensConfig {
  const SliderThemeTokensConfig._();

  /// Global component theme override for `SliderTheme`.
  static Object? global;
  static const String globalType = 'SliderTheme';
  static const Map<String, Object?> globalDefaults = <String, Object?>{
    'trackHeight': 'baseGap * 3.5',
    'trackRadius': 'theme.radiusLg',
    'thumbInset': 'baseGap * 1.25',
    'thumbSize': null,
    'thumbRadius': null,
    'thumbEdgeOffsetPx': null,
    'thumbVerticalOffsetPx': 0.0,
    'joinGapPx': 'baseGap * 0.25',
    'fillStopsAtThumbCenter': true,
    'fillEdgeBiasPx': 0.0,
    'preset': 'widget.isRange ? \'rangeSoft\' : \'brightness\'',
    'trackBuilder': null,
    'fillBuilder': null,
    'thumbBuilder': null,
    'ticksBuilder': null,
    'overlayBuilder': null,
    'segmentLayout': null,
    'trackRenderer': null,
    'dragPopoverBuilder': null,
    'dragPopoverOffset': 'const Offset(0, -12)',
    'dragPopoverVisibility': 'ShadPopoverVisibility.whileDragging',
    'popoverShape': null,
    'popoverBackgroundColor': null,
    'popoverForegroundColor': null,
    'guideColor': null,
    'fillActiveColor': null,
    'fillInactiveColor': null,
    'thumbFillColor': null,
    'thumbBorderColor': null,
    'dotsActiveColor': null,
    'dotsInactiveColor': null,
    'waveformTicksActiveColor': null,
    'waveformTicksInactiveColor': null,
    'waveHeight': null,
    'wavePadding': null,
    'waveBarWidth': null,
    'waveBarGap': null,
    'waveMinBarHeight': null,
    'waveMaxBarHeight': null,
    'waveCornerRadius': null,
    'waveActiveColor': null,
    'waveInactiveColor': null,
    'waveDisabledOpacity': null,
    'waveShowThumb': null,
    'waveThumbRadius': null,
    'waveThumbColor': null,
    'waveThumbBorderColor': null,
    'waveThumbBorderWidth': null,
    'waveHitSlop': null,
    'waveEnabled': null,
    'wavePopoverBuilder': null,
    'wavePopoverOffset': null,
    'wavePopoverVisibility': null,
  };
  static const Map<String, Object?> globalTokens = <String, Object?>{};
}
