import 'package:flutter/widgets.dart';
import '../../component_example_models.dart';
import 'navigation_sidebar_example_1.dart';

const ComponentExample navigationSidebarExample1 = ComponentExample(
  title: "Example",
  builder: _buildNavigationSidebarExample1,
  code: "import 'package:docs/shadcn_ui.dart';\n\n// Demonstrates a vertical NavigationSidebar with labels, dividers, and gaps.\n// Selection is index-based and controlled by local state.\n\nclass NavigationSidebarExample1 extends StatefulWidget {\n  const NavigationSidebarExample1({super.key});\n\n  @override\n  State<NavigationSidebarExample1> createState() =>\n      _NavigationSidebarExample1State();\n}\n\nclass _NavigationSidebarExample1State extends State<NavigationSidebarExample1> {\n  // Currently selected item index in the sidebar.\n  int selected = 0;\n\n  NavigationBarItem buildButton(String label, IconData icon) {\n    // Helper for a standard navigation item with text label and icon.\n    return NavigationItem(\n      label: Text(label),\n      child: Icon(icon),\n    );\n  }\n\n  @override\n  Widget build(BuildContext context) {\n    return SizedBox(\n      height: 400,\n      child: OutlinedContainer(\n        child: NavigationSidebar(\n          // Wire selection to local state.\n          index: selected,\n          onSelected: (index) {\n            setState(() {\n              selected = index;\n            });\n          },\n          children: [\n            // A mix of labels, gaps, dividers, and items can be used to\n            // structure the navigation list into logical sections.\n            const NavigationLabel(child: Text('Discovery')),\n            buildButton('Listen Now', BootstrapIcons.playCircle),\n            buildButton('Browse', BootstrapIcons.grid),\n            buildButton('Radio', BootstrapIcons.broadcast),\n            const NavigationGap(24),\n            const NavigationDivider(),\n            const NavigationLabel(child: Text('Library')),\n            buildButton('Playlist', BootstrapIcons.musicNoteList),\n            buildButton('Songs', BootstrapIcons.musicNote),\n            buildButton('For You', BootstrapIcons.person),\n            buildButton('Artists', BootstrapIcons.mic),\n            buildButton('Albums', BootstrapIcons.record2),\n            const NavigationGap(24),\n            const NavigationDivider(),\n            const NavigationLabel(child: Text('Playlists')),\n            buildButton('Recently Added', BootstrapIcons.musicNoteList),\n            buildButton('Recently Played', BootstrapIcons.musicNoteList),\n            buildButton('Top Songs', BootstrapIcons.musicNoteList),\n            buildButton('Top Albums', BootstrapIcons.musicNoteList),\n            buildButton('Top Artists', BootstrapIcons.musicNoteList),\n            buildButton('Logic Discography With Some Spice',\n                BootstrapIcons.musicNoteList),\n            buildButton('Bedtime Beats', BootstrapIcons.musicNoteList),\n            buildButton('Feeling Happy', BootstrapIcons.musicNoteList),\n            buildButton('I miss Y2K Pop', BootstrapIcons.musicNoteList),\n            buildButton('Runtober', BootstrapIcons.musicNoteList),\n          ],\n        ),\n      ),\n    );\n  }\n}\n",
);

Widget _buildNavigationSidebarExample1(BuildContext context) {
  return const NavigationSidebarExample1();
}

const List<ComponentExample> navigationSidebarExamples = [
  navigationSidebarExample1,
];
