name: docs
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.3
  shared_preferences: ^2.3.2
  http: ^1.2.2
  widget_visibility_checker: ^1.0.2
  visibility_detector: ^0.4.0+2
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  yaml: ^3.1.3
  syntax_highlight: ^0.5.0
  web: ^1.1.1
  file_picker: 10.3.9
  data_widget: ^0.0.2
  gap: ^3.0.1
  animation_kit: ^0.0.2
  country_flags: ^4.1.1
  cross_file: ^0.3.4+2
  email_validator: ^3.0.0
  expressions: ^0.2.5+2
  flutter_localizations:
    sdk: flutter
  intl: any
  phonecodes: ^0.0.4
  skeletonizer: ^2.1.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: LucideIcons
      fonts:
        - asset: assets/fonts/lucide.ttf
    - family: RadixIcons
      fonts:
        - asset: assets/fonts/radix.otf
    - family: BootstrapIcons
      fonts:
        - asset: assets/fonts/bootstrap.otf
    - family: NotoSansSymbols2
      fonts:
        - asset: assets/fonts/NotoSansSymbols2-Regular.ttf
    - family: GeistSans
      fonts:
        - asset: assets/fonts/Geist-Black.otf
          weight: 800
        - asset: assets/fonts/Geist-BlackItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Geist-Bold.otf
          weight: 700
        - asset: assets/fonts/Geist-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Geist-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/Geist-Light.otf
          weight: 300
        - asset: assets/fonts/Geist-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Geist-Medium.otf
          weight: 500
        - asset: assets/fonts/Geist-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Geist-Regular.otf
          weight: 400
        - asset: assets/fonts/Geist-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Geist-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Geist-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Geist-Thin.otf
          weight: 100
        - asset: assets/fonts/Geist-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/Geist-UltraBlack.otf
          weight: 900
        - asset: assets/fonts/Geist-UltraLight.otf
          weight: 200
    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono-Black.otf
          weight: 800
        - asset: assets/fonts/GeistMono-BlackItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/GeistMono-Bold.otf
          weight: 700
        - asset: assets/fonts/GeistMono-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/GeistMono-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/GeistMono-Italic.otf
          style: italic
        - asset: assets/fonts/GeistMono-Light.otf
          weight: 300
        - asset: assets/fonts/GeistMono-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/GeistMono-Medium.otf
          weight: 500
        - asset: assets/fonts/GeistMono-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/GeistMono-Regular.otf
          weight: 400
        - asset: assets/fonts/GeistMono-SemiBold.otf
          weight: 600
        - asset: assets/fonts/GeistMono-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/GeistMono-Thin.otf
          weight: 100
        - asset: assets/fonts/GeistMono-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/GeistMono-UltraBlack.otf
          weight: 900
        - asset: assets/fonts/GeistMono-UltraLight.otf
          weight: 200
  assets:
    - assets/docs_images/
    - assets/fonts/geist/Geist-Black.otf
    - assets/fonts/geist/Geist-BlackItalic.otf
    - assets/fonts/geist/Geist-Bold.otf
    - assets/fonts/geist/Geist-BoldItalic.otf
    - assets/fonts/geist/Geist-ExtraLightItalic.otf
    - assets/fonts/geist/Geist-Light.otf
    - assets/fonts/geist/Geist-LightItalic.otf
    - assets/fonts/geist/Geist-Medium.otf
    - assets/fonts/geist/Geist-MediumItalic.otf
    - assets/fonts/geist/Geist-Regular.otf
    - assets/fonts/geist/Geist-RegularItalic.otf
    - assets/fonts/geist/Geist-SemiBold.otf
    - assets/fonts/geist/Geist-SemiBoldItalic.otf
    - assets/fonts/geist/Geist-Thin.otf
    - assets/fonts/geist/Geist-ThinItalic.otf
    - assets/fonts/geist/Geist-UltraBlack.otf
    - assets/fonts/geist/Geist-UltraLight.otf
    - assets/fonts/geist/GeistMono-Black.otf
    - assets/fonts/geist/GeistMono-BlackItalic.otf
    - assets/fonts/geist/GeistMono-Bold.otf
    - assets/fonts/geist/GeistMono-BoldItalic.otf
    - assets/fonts/geist/GeistMono-ExtraLightItalic.otf
    - assets/fonts/geist/GeistMono-Italic.otf
    - assets/fonts/geist/GeistMono-Light.otf
    - assets/fonts/geist/GeistMono-LightItalic.otf
    - assets/fonts/geist/GeistMono-Medium.otf
    - assets/fonts/geist/GeistMono-MediumItalic.otf
    - assets/fonts/geist/GeistMono-Regular.otf
    - assets/fonts/geist/GeistMono-SemiBold.otf
    - assets/fonts/geist/GeistMono-SemiBoldItalic.otf
    - assets/fonts/geist/GeistMono-Thin.otf
    - assets/fonts/geist/GeistMono-ThinItalic.otf
    - assets/fonts/geist/GeistMono-UltraBlack.otf
    - assets/fonts/geist/GeistMono-UltraLight.otf
    - assets/markdown/
    - assets/registry/components.json
    - docs.json
    - pubspec.lock
