import 'package:data_widget/data_widget.dart';
import 'package:flutter/material.dart' show Colors, VerticalDivider;
import 'package:flutter/widgets.dart';

import '../button/button.dart';
import '../sortable/sortable.dart';
import '../../shared/primitives/fade_scroll.dart';
import '../../shared/primitives/outlined_container.dart';
import '../../shared/theme/theme.dart';
import '../../shared/utils/geometry_extensions.dart';
import '../../shared/utils/style_value.dart';
import '../../shared/utils/util.dart';

part '_impl/tabs_text_styles.dart';
part '_impl/tabs_theme.dart';
part '_impl/tabs_widget.dart';
part '_impl/tab_list_theme.dart';
part '_impl/tab_list.dart';
part '_impl/tab_container_theme.dart';
part '_impl/tab_container_data.dart';
part '_impl/tab_child_widget.dart';
part '_impl/keyed_tab_child_widget.dart';
part '_impl/tab_item.dart';
part '_impl/keyed_tab_item.dart';
part '_impl/tab_builder_typedefs.dart';
part '_impl/tab_container.dart';
part '_impl/tab_pane_theme.dart';
part '_impl/tab_pane_data.dart';
part '_impl/tab_pane_typedefs.dart';
part '_impl/tab_pane_widget.dart';
part '_impl/tab_ghost_data.dart';
part '_impl/tab_pane_state.dart';
part '_impl/tab_item_painter.dart';
part '_impl/clip_rect_with_adjustment.dart';
